### ISSUE TITLE
serve static example not working

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp#10]
Hi, I'm interested in developing APIs with deno but not with the plain oak but with a more opinionated way.

I try to reproduce the serve static example from: https://github.com/nhttp/nhttp/blob/master/examples/serve-static.ts

Here is my code:

```ts
import { NHttp } from "https://deno.land/x/nhttp@1.1.11/mod.ts";
import staticFiles from "https://deno.land/x/static_files@1.1.4/mod.ts";

const app = new NHttp();

app.use("/", staticFiles("public"));
// app.use(staticFiles("public"));

app.listen(3000, () => {
  console.log("> Running on port 3000");
});
```

Everything I get if I go to `http://localhost:3000/` is:
` {"status":404,"message":"Route GET/ not found","name":"NotFoundError"}`

Maybe I'm doing it wrong or was there a bug introduced?

**Comment by herudi** [comment]
thanks for creating issue. but, what is the expected result ?. 
if get from `http://localhost:3000/` without index in public folder, will redirect to 404.

**Comment by zingmane** [comment]
Ah, seems to be a problem with the path resolution. I started the server from outside the project with `deno run -A nhttp_test/serve_static.ts`. If I cd into the project dir and run with `cd nhttp_test && deno run -A serve_static.ts`, then everything is working. 

![image](https://user-images.githubusercontent.com/148202/216280267-4f035ebf-6bd2-4ad0-ab81-8185d2458b92.png)

**Comment by herudi** [comment]
yes of course. must resolve dir. if you want to run from outside the project, you can try this method without deps: 
```ts
...
const dir = new URL("public", import.meta.url).href;
app.use(staticFiles(dir));
...
```

hope this helps.

**Comment by zingmane** [comment]
Thanks a lot 👍
