### ISSUE TITLE
Bun nHttp react ssr. Build failed.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#101]
Hi @herudi ,

I'm getting this error when i run : bun run build . I use bun nHttp react ssr.

![Screenshot from 2024-09-20 09-46-00](https://github.com/user-attachments/assets/c590edbc-3a4f-4f71-9ce5-f694fc8ff42b)

**Comment by herudi** [comment]
try to set platform to node in esbuild config.ts.

**Comment by herudi** [comment]
to change/add html/body attr, just add html/body tag in Helmet. `<html lang="id"/>` or `<body class="foo"/>`.

Unfortunately, I'm not a Vue user. so I can't help you.

**Comment by herudi** [comment]
currently, not support.
