### ISSUE TITLE
zod declaration and validation [idea / feature request]

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp#11]
Are there any plans or considerations to introduce [zod](https://github.com/colinhacks/zod) as first class validator for nhttp?

Honestly, I have to say that I've never used zod before, but it looks very promising to me because you have type safety at both runtime and type level.

Currently one has to define the schema once for the validation at runtime, which one can also use for the generation of the OpenApi Spec. 
And a second time for the type safety, to be able to continue working with the parsed body.

**Comment by herudi** [comment]
interesting with zod. 
btw, nhttp is simple to integrate with zod-validator. this is an example with body validation zod.
```ts
import nhttp, { Handler, HttpError } from "https://deno.land/x/nhttp@1.2.3/mod.ts";
import { z, ZodType } from "https://deno.land/x/zod@v3.21.4/mod.ts";

// create middleware validator.
// save to zod_validator.ts
const validate = (schema: ZodType): Handler => (rev, next) => {
  try {
    schema.parse(rev.body);
    return next();
  } catch (e) {
    throw new HttpError(422, e.errors);
  }
}

// define User
const User = z.object({
  username: z.string(),
});

// Type User
type TUser = z.infer<typeof User>;

const app = nhttp();

app.post("/", validate(User), (rev) => {
  const user = <TUser> rev.body;
  // now user is typesafe
  return user;
});

app.listen(8000);
```

**Comment by zingmane** [comment]
Thanks @herudi for implementing zod validation with version https://github.com/nhttp/nhttp/releases/tag/1.2.7

**Comment by herudi** [comment]
You're welcome. 
Doc => https://nhttp.deno.dev/docs/3rd-party-lib/zod-validator
