### ISSUE TITLE
Connection abortion when returning void

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp#12]
Returning `Promise<void>` should response with an empty body.

My code:

```ts
@Controller("/entity")
export class MyController {

  @ApiParameter(paramId)
  @Delete("/:id")
  @Status(204) // same with 200
  deleteSomeEntity(rev: RequestEvent) {
    const { id } = rev.params;
    return doDelete(id);
  }
}

const doDelete = (_id: number): Promise<void> => {
  return Promise.resolve();
};
```

Request to `/entity/1337` results in `http: error: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) while doing a DELETE request to URL: http://localhost:4001/api/entity/1337`

Awaiting the promise and explicitly returning `null` works as expected, e.g. with `return doDelete(id).then(() => null)`.
Returning `new Response(null, { status: 200 });` also works.

I think 'void' should be translated to an empty body.

**Comment by herudi** [comment]
Returning `void`, it's the same as returning `undefined`. and it's the same when a `handler` returns nothing.
```ts
// example 
app.get("/", () => {
   //send nothing or blank response. expressjs or other popular frameworks alike.
});
```
the solution in your case :
```ts
const doDelete = (_id: number): Promise<void> => {
  return Promise.resolve(null);
};
```

or you can try this: 
```ts
@Controller("/entity")
export class MyController {

  @ApiParameter(paramId)
  @Delete("/:id")
  @Status(204) // same with 200
  async deleteSomeEntity(rev: RequestEvent) {
    const { id } = rev.params;
    await doDelete(id);
    return null;
  }
}

const doDelete = (_id: number): Promise<void> => {
  return Promise.resolve();
};

```

Hope this help.

**Comment by zingmane** [comment]
Yes, as I indicated, explicitly returning something other than undefined solves the problem. 
I just thought that this can be solved in general. 
If the behavior is the same for express and others, I think that's fine too.
