### ISSUE TITLE
Using https and Letsencrypt certificate problem.

### ISSUE THREAD

**Issue by jacorall** [nhttp/nhttp#18]
Hi

I'm having a problem getting HTTPS to work.  I'm sure I'm doing something wrong.  The app just exits, and does not continue listening.

I normally use NginX Reverse Proxy manager to access the deno web app.
I now have a scenario where I have to run the web app and listen on port 443, and use a Lets Encrypt certificate.

I created a Debian VM on Digital Ocean and use Certbot to get and renew the certificate for api.notrealname.com (not the actual domain name).
The cert and key get stored at the following locations:
"cert": "/etc/letsencrypt/live/api.notrealname.com/fullchain.pem",
"key": "/etc/letsencrypt/live/api.notrealname.com/privkey.pem",

I've created the following test app:
```
import nhttp from "https://deno.land/x/nhttp@1.2.19/mod.ts";
import settings from "./settings.json" assert { type: "json" };

const app = nhttp();

app.get("/", () => {
   return "Hi";
})

app.listen({
   port:443, 
   cert: settings.cert, 
   key: settings.key, 
   alpnProtocols: ["h2", "http/1.1"]
});
```
The settings.json file looks like this:
```
{
	"cert": "/etc/letsencrypt/live/api.notrealname.com/fullchain.pem",
	"key": "/etc/letsencrypt/live/api.notrealname.com/privkey.pem",
}
```

**Comment by herudi** [comment]
try this. to show error. 
```ts
app.listen(options, (err) => {
  console.log(err);
});
```

**Comment by jacorall** [comment]
Thank you for the advice.

I've change the test app.js to be as follows:
```
import nhttp from "https://deno.land/x/nhttp@1.2.19/mod.ts";
import settings from "./settings.json" assert { type: "json" };

const app = nhttp();

app.get("/", () => {
   return "Hi";
})

let callback;

const options = {
   port:443, 
   cert: settings.cert, 
   key: settings.key, 
   alpnProtocols: ["h2", "http/1.1"]
};

app.listen(options, (err) => {
   console.log(err);
 });
```
The error it give is:
```
InvalidData: No certificates found in cert file
    at listenTls (ext:deno_net/02_tls.js:72:40)
    at NHttp.listen (https://deno.land/x/nhttp@1.2.19/src/nhttp.ts:366:61)
    at file:///root/test/test.js:19:5 {
  name: "InvalidData"
}

```
I confirmed that the certificate and key file contains data.

I used `deno run --allow-env --allow-write --allow-net --allow-run --allow-read --unstable --no-check test.js` for the test.

**Comment by herudi** [comment]
the certificate not found. solution, try using fileUrl e.g `file:///etc/mykey.cert`. cause the cert files outside the project. 
please the following instruction https://deno.com/manual@v1.34.1/runtime/http_server_apis#https-support

**Comment by jacorall** [comment]
I changed "key" to "keyFile" and cert to "certFile", and now it works:
```
import nhttp from "https://deno.land/x/nhttp@1.2.19/mod.ts";
import settings from "./settings.json" assert { type: "json" };

const app = nhttp();

app.get("/", () => {
   return "Hi";
})

let callback;

const options = {
   port:443, 
   certFile: settings.cert, 
   keyFile: settings.key, 
   alpnProtocols: ["h2", "http/1.1"]
};

app.listen(options, (err) => {
   console.log(err);
 });
```

**Comment by jacorall** [comment]
Thank you for your help.
