### ISSUE TITLE
Matches from RegExp route?

### ISSUE THREAD

**Issue by eevleevs** [nhttp/nhttp#23]
Is there a way to get the matching groups for a route defined by RegExp?

**Comment by herudi** [comment]
```ts
// RegExp. match for path endsWith ball. ex: /dragonball or /football
app.get(/.*ball$/, (rev) => {
  return rev.path;
});
```

**Comment by eevleevs** [comment]
Figured this one, but will require another match to extract `dragon` from `/(.*)ball$/`. I thought groups could be made already available, but I see it's not trivial.
