### ISSUE TITLE
how to use graphql with nhttp ?

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#25]
how to use graphql with nhttp ?

**Comment by MrFoxPro** [comment]
Would like to see example of this too.

**Comment by herudi** [comment]
interested, to make an example with graphql. i will make it soon.

**Comment by herudi** [comment]
example with graphql => https://github.com/nhttp/nhttp/blob/master/examples/with-graphql.ts. 
featuring [graphql-yoga](https://github.com/dotansimha/graphql-yoga)

**Comment by MrFoxPro** [comment]
`void 0` :D
Thank you!

**Comment by francelwebdev** [comment]
Thank you!
