### ISSUE TITLE
Property 'handler' does not exist on type 'Server<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>'

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#31]
Hi,
I'm getting : Property 'handler' does not exist on type 'Server<DefaultEventsMap, DefaultEventsMap, DefaultEventsMap, any>' when i try to use socket.io with NHttp and nodejs.

const wsHandler = io.handler(app.handle);

**Comment by herudi** [comment]
maybe fix in here #20 for nodejs.
