### ISSUE TITLE
Error cors

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#32]
Access to XMLHttpRequest at 'http://localhost:3000/api/users/login' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:9000,https://ciexchange.pages.dev,https://ciexchange.francel.xyz', but only one is allowed.

**Comment by herudi** [comment]
please update to 1.3.7
