### ISSUE TITLE
Serve static fail

### ISSUE THREAD

**Issue by michailVestnik** [nhttp/nhttp#4]
Hi! 

I used your example at: https://github.com/nhttp/nhttp/blob/master/examples/serve-static.ts
... and everything works fine. 

![Снимок экрана от 2021-07-06 13-16-02](https://user-images.githubusercontent.com/75129392/124541732-fee96c00-de5c-11eb-8aa7-aafb5e043cbe.png)

## problem

But as soon as I create a folder CSS and in the html document specify the path - everything stops working!

## my example

```js 
const app = new Application()

app.use('/', statics('static'))

app.get('/', function index(response) {
    return response.send('./static/index.html')
})

app.listen(8080, () => {
    console.log('!')
})
```

Спасибо!

**Comment by herudi** [comment]
@michailVestnik Please provide information about nhttp and staticFiles version. and please provide the complete code. maybe by creating a public repo by you. I will fix it soon. thanks for creating this issue.

**Comment by michailVestnik** [comment]
I really liked nhttp, but I test a lot before I take something. 
I found some more interesting and uncharacteristic bugs for Deno...

## versions

Nhttp 0.7.2
static_files 1.0.3

## All complete code

```js
import { NHttp as Application } from 'https://deno.land/x/nhttp@0.7.2/mod.ts'
import{ default as statics } from 'https://deno.land/x/static_files@1.0.3/mod.ts'

const app = new Application()

app.use('/', statics('static'))

app.get('/',function({response}) {

    console.log(response)
    // unexpectedly console.log not work !!!

    response.cookie("key", "value", {
        HttpOnly: true,
        maxAge: 60 * 60,
        encode: true
    })
    // cookie not work !!!

    // serve static files without request in app.get !!!

})

app.listen(8080, () => {
    console.log('!')
})
```

**Comment by herudi** [comment]
@michailVestnik I found your problem. that's because 2 routes have the same url `/`. then it will execute the first one only. if you want to send cookies just setHeaders in staticFiles.

```ts
import { NHttp as Application } from 'https://deno.land/x/nhttp@0.7.2/mod.ts'
import{ default as statics } from 'https://deno.land/x/static_files@1.0.3/mod.ts'

const app = new Application();

app.use('/', statics('static', {
    etag: false,
    setHeaders(headers, path, stats){
        headers.set("Set-Cookie", "key=value; HttpOnly; Path=/;")
    }
}));

app.listen(8080, () => {
    console.log('!')
})
```

I hope this helps.

**Comment by michailVestnik** [comment]
Thank you so much for your help!

**Comment by herudi** [comment]
Ur welcome...
