### ISSUE TITLE
Build errors because of unpinned esm.sh version

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp#40]
In my build I get this error message from time to time though I'm using a deno.lock:

```
The source code is invalid, as it does not match the expected hash in the lock file.
  error: The source code is invalid, as it does not match the expected hash in the lock file.
    Specifier: https://esm.sh/class-validator@0.14.0
    Lock file: /app/packages/backend/deno.lock
```

All my dependencies are pinned to fixed versions and esm.sh deps are also pinned to fixed esm.sh build versions.
I think the unpinned Version error comes from a transitive dependency of nhttp. -> https://github.com/nhttp/nhttp/blob/master/lib/class-validator.ts#L4C34-L4C34

I think the best way to fix that is to also pin the esm.sh version in your deps.
Further info is at https://esm.sh in docs and faq section, look for `The source code is invalid,...`

**Comment by herudi** [comment]
Hi @zingmane You can try integrity-checking. doc => https://deno.land/manual@v1.36.4/basics/modules/integrity_checking.

```bash
deno cache --lock=deno.lock --lock-write deps.ts
```
the `class-validator` version on your machine, is different from the url.

**Comment by zingmane** [comment]
The problem is the url, because it is not pinned. 
What you suggest is exactly what I'm doing on every esm.sh version change.

Currently, the latest esm.sh build is v132. If they bump the version, integrity check will fail, even if the class-validator version didn't change, because of different hashes. This is described on their site.
If I then rewrite the lockfile, everything is ok until the next version bump.

I only notice the error when the build server is running on error.

**Comment by herudi** [comment]
Yes you're right. rewriting the lock file is temporary. requires a stable build version of esm.sh. it just add the pin in path to esm.sh.
```bash
https://esm.sh/v132/lib-name
```

Can you make PRs to solve this problem? 
Thank's for creating this issue.

**Comment by herudi** [comment]
publish to v1.3.10 => https://deno.land/x/nhttp@1.3.10
