### ISSUE TITLE
the tsconfig.json generated by the cli not including default outDir and rootDir and also an build script in package.json for Nodejs.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#44]
Hello Sir,

- the tsconfig.json generated by the cli not including default outDir and rootDir and also an build script in package.json for Nodejs.
- just like jsx support, vuejs support would be cool too

Thanks Sir

**Comment by herudi** [comment]
Sorry, your issue/question is not related here. please write about this issue again at https://github.com/nhttp/create-nhttp
