### ISSUE TITLE
How to make api-docs using Swagger without controller Decorators, but with router app.METHOD style ?

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#45]
Hello Sir,
Hope your are well.
Please, how to make api-docs using Swagger without controller Decorators, but with router app.METHOD style.
Thanks

**Comment by herudi** [comment]
for me, not recommended and not supported yet. like [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express), you have to define the API spec manually. for now, decorator is the right choice.

**Comment by herudi** [comment]
select `MVC` template.

**Comment by herudi** [comment]
in MVC, is not using react. but you can support to react.
```ts
options.onRenderElement = (elem) => {
  Helmet.render = renderToString;
  const body = Helmet.render(elem);
  return body;
};
```
example => https://github.com/nhttp/nhttp/blob/master/examples/with-react.tsx
and just change jsxImportSource to `react` in tsconfig.json

in the controller, you can use ext `tsx`, `ts`, `js` or `jsx`. but `tsx` is recommended.


in validation, please create one validation for better type. perhaps an ambiguity in your schema.
