### ISSUE TITLE
`rev.request` not 100% the original one

### ISSUE THREAD

**Issue by shevernitskiy** [nhttp/nhttp#49]
Body of the `rev.request` counted as consumed.
This is not a big deal, but it can block to use libs, which expects body as stream to perform `.json()` (for example).

For example, bot framework https://grammy.dev/ has a webhook handler, that can accept `Request` and do the work. But with nhttp it is not possible. There is only option to make a special adapter for grammy.

**Comment by herudi** [comment]
try with `rev.newRequest`. 

https://nhttp.deno.dev/docs/request-event/new-request

**Comment by shevernitskiy** [comment]
oh, thanks!
