### ISSUE TITLE
Add exemple of Session-Based Authentication

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#51]
Add exemple of Session-Based Authentication

**Comment by herudi** [comment]
if you understand the concept of middleware, it should be easy.
just send cookie using `rev.response.cookie` and get request cookies using `rev.cookies`.
Example session views : 
```ts

const app = nhttp();

app.use((rev, next) => {
  rev.views = () => {
    const views = parseInt(rev.cookies.views ?? "0") + 1;
    rev.response.cookie("views", views, { encode: true });
    return views;
  }
  return next();
});

app.get("/", (rev) => {
  return `Page views ${rev.views()} times`;
});

app.listen(8080, (_err, info) => {
  console.log(`Running on port ${info.port}`);
});
```

Basic Session Auth => https://github.com/nhttp/nhttp/blob/master/examples/basic-auth.ts
