### ISSUE TITLE
problem with CORS in production

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#53]
Hello, I have had a problem for a while with an API that I built with NHttp and Nodejs which is running in production.
Every time the spa vuejs frontend hosted on cloudflare page sends a request to the api after a certain time of inactivity (8hour...) the frontend request does not reach the server and I often get errors CORS in the browser console.

![Screenshot from 2023-10-23 08-23-48](https://github.com/nhttp/nhttp/assets/18377068/145cddca-8798-46bd-ae93-a5a0eb6e0c62)

**Comment by herudi** [comment]
maybe I can see the cors configuration?

**Comment by herudi** [comment]
preflightNext is the same as preflightContinue in expressjs. You can try changing it to false or not set.
