### ISSUE TITLE
is there a way to set a timeout for specific controller or request endpoints?

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp#57]
I'm not sure how or where timeouts are handled. I only get problems with my client if a request takes longer than 11_000ms -> `408 Request Timeout`.

For endpoints that perform longer data processing operations, I would like to increase this timeout. I can't find any hint in the docs, is this possible?

**Comment by zingmane** [comment]
It seems as if I have found a way. But it feels ugly. It would be better to set a max timeout e.g. 20 seconds, and if the promise is not resolved within this period, the server should respond with 408.
Here is my workaround for now.

```ts
@ApiDocument({ name: "system" })
@Controller("/system")
export class SystemController {
  @Get("/info")
  getInfo(rev: RequestEvent) {
    const opThatLasts = (ms: number): Promise<string> =>
    new Promise((resolve) => {
      setTimeout(() => {
        resolve("ok");
      }, ms);
    });

    const resultPromise = opThatLasts(20_000);
    rev.waitUntil(resultPromise);

    return rev.respondWith(resultPromise as any);
    // return resultPromise;
  }
}
```

**Comment by zingmane** [comment]
That doesn't solve the problem in the case that both timeouts are larger than the magical 11 seconds.
If I do following, all promises will resolve asynchronously, but the client that calls the endpoint still receives a timeout 408 after 11 seconds. 

```ts
const withTimeout = (p: Promise<any>, ms: number) =>
  Promise.race([
    p,
    new Promise((res) => setTimeout(res, ms)).then(() => {
      console.log("log from inside first promise");
      throw new HttpError(408);
    }),
  ]);
  
app.get("/", async () => {
  console.log("log incoming request");
  const myProcess = () => {
    console.log("log from inside second promise");
    return new Promise((res) => setTimeout(res, 15_000));
  };
  await withTimeout(myProcess(), 20_000);
  console.log("log after await");
  return "done!";
});
```

I think I have to increase the internal time out somehow to solve the problem.

**Comment by herudi** [comment]
how about this? 
```ts
// timeout 11s.
await withTimeout(myProcess(), 11000);
```

BTW in nodejs, set timeout server with `server.setTimeout`. but i don't know the config in deno.

**Comment by zingmane** [comment]
I think you have misunderstood me. I want the response to wait longer for resolving the process promise not to reduce the default time to something less than the magic 11_000ms. 
I have found out what the problem is. It is the awaiter function in `nhttp_utils.ts`, which works with "hardcoded" timeouts.
It checks in unequal periods if the response is still resolved:

- sleep 0ms -> check response
- sleep another 200ms -> check response
- sleep another 400ms -> check response
- sleep another 600ms -> check response
- sleep another 800ms -> check response
- sleep another 1000ms -> check response
- sleep another 1200ms -> check response
- sleep another 1400ms -> check response
- sleep another 1600ms -> check response
- sleep another 1800ms -> check response
- sleep another 2000ms -> check response (sums up to 11_000ms) -> if still no response, return 408

https://github.com/nhttp/nhttp/blob/86f541ed3349504f2d35688f7a8b49661b484862/src/nhttp_util.ts#L5-L24

Shouldn't there be a smarter implementation? Or shouldn't there at least be a way to inject a custom timeout from outside to override the defaults?

**Comment by herudi** [comment]
Oh I see. The code is wait and timeout for undefined returns on a handler. if there is a response, then `awaiter` is not executed. 

maybe I will give a timeout value option in the `nhttp` config to handle this. what do you think?. or have any ideas?

**Comment by herudi** [comment]
as I mentioned, there is no timeout feature in Deno. and if you adopt the expressjs feature, it will be more or less like this..

```ts
const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

// this is similar req.setTimeout in express but in middleware.
const timeout = (ms: number): Handler => (_, next) => {
  return Promise.race([
    next(),
    wait(ms).then(() => next(new HttpError(408))),
  ]);
};

const app = nhttp();

app.get("/", timeout(11000), async () => {
  // asume process save to db 20s and request timeout is 11s. so this routes reject to 408.
  await wait(20000);
  return "done";
});
```

in Expressjs
```ts
const app = express();

app.get("/", async (req, res) => {
  req.setTimeout(11000);
  await wait(20000);
  res.send("done");
});
```

**Comment by zingmane** [comment]
I'm sorry, no, that doesn't solve the problem. With the timeoutHandler I can reduce the timeout but not increase it beyond above the 11 seconds, because this does not bypass the `awaiter` logic and with `Promise.race` an HttpError(408) is always returned for the shortest time period.

As long as there is no way to set a global timeout in  `nhttp`, I go with my first working workaround (waitUntil + respondWith).

Thx

**Comment by zingmane** [comment]
I'm not sure. Maybe the problem is the swagger wrapper I'm using? I don't know the internals but could it be the problem, that the return value is not registered in `rev[s_response]` so I'm running into the 'awaiter' logic.

This is how I use it, which internally calls the 'awaiter':

```ts
@ApiDocument({ name: "system" })
@Controller("/system")
export class SystemController {
  @Get("/info")
  getInfo(rev: RequestEvent) {
    const resultPromise = anyMethodThatResolvesAfter11Seconds(20_000);
    return anyMethodThatResolvesAfter11Seconds(20_000);
  }
}

const anyMethodThatResolvesAfter11Seconds = (ms: number) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve("ok");
    }, ms);
  });
}
```

**Comment by herudi** [comment]
i tested in my laptop, and work fine as expected.
```ts
@ApiDocument({ name: "system" })
@Controller("/system")
export class SystemController {

  @Get("/info")
  getInfo(rev: RequestEvent) {
    return anyMethodThatResolvesAfter11Seconds(20_000);
  }
}

const anyMethodThatResolvesAfter11Seconds = (ms: number) => {
  return new Promise((resolve) => {
    const now = Date.now();
    setTimeout(() => {
      // resolve 20000ms
      resolve(`${Date.now() - now}ms`);
    }, ms);
  });
}
```

**Comment by zingmane** [comment]
That's really strange. I copied your code to have it exactly the same, but I still get a timeout with that code after 11 seconds 🤔
Also upgraded from `nhttp` 1.3.10 -> 1.3.13 and using these imports, but had no effect:
```ts
"nhttp_controller": "https://deno.land/x/nhttp@1.3.13/lib/controller.ts",
"nhttp_swagger": "https://deno.land/x/nhttp@1.3.13/lib/swagger.ts",
"nhttp_validator": "https://deno.land/x/nhttp@1.3.13/lib/class-validator.ts"
```

**Comment by zingmane** [comment]
Oh dear, I was just about to set up a simple project to reproduce the error. Then I realized that everything works as it should, as you say. 🙈

I analyzed everything and found that the `return` before the `next()` is missing in one of my middlewares. 😔

Thanks for the always fast and great help and sorry that the error was mine.
