### ISSUE TITLE
When will vuejs ssr support be ready ?

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#65]
Hello, I'm doing VueJS on the front end and I'm looking for a way to build a complete application without making a separate API and separate VueJS frontend. When will vuejs ssr support be ready? Thanks a lot. I currently use nhttp as a separate api and a second vuejs project as a frontend and I feel exhausted working on both at the same time.

**Comment by herudi** [comment]
sorry, not in this project. But it will be in [create-nhttp](https://github.com/nhttp/create-nhttp). 
I'll let you know here when it's there. thanks.
