### ISSUE TITLE
can't use a folder array as first parameter of serveStatic()

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#66]
can't use a folder array as first parameter of serveStatic().

also the code below not working

this.use("/assets", serveStatic("node_modules", { etag: true }));
this.use("/assets", serveStatic("public", { etag: true }));

**Comment by herudi** [comment]
try using `prefix` path like this :
```ts
this.use(serveStatic("node_modules", { etag: true, prefix: "/assets" }));
this.use(serveStatic("public", { etag: true, prefix: "/assets" }));
```

related to => https://nhttp.deno.dev/docs/3rd-party-lib/serve-static#usage
