### ISSUE TITLE
request.body breaks for large bodies(?)

### ISSUE THREAD

**Issue by xyzshantaram** [nhttp/nhttp#74]
For some reason, the automatic request body parsing doesn't work for the following snippet. `request.json()` functions normally.

The JSON body being sent is ~1.3mb of image data encoded as base64 along with a couple of other fields.

```ts
app.post("/file", async ({ body, response, headers, request }) => {
        console.log(await request.json()); // correct body
        const token = headers.get("Authorization");
        const [msg, result] = await checkToken(token);
        if (msg) return error(response)(msg);

        console.log('upload', body); // upload {}

        const uuid = crypto.randomUUID();
        const type = headers.get("Content-Type");
        if (!type) return error(response)("Content type of file must be specified!");

        const metadata = body.metadata ? JSON.stringify(body.metadata) : undefined;

        await db.put(["files", uuid], {
            uploader: result!.username,
            data: body.contents,
            metadata,
            type
        });
        return { uuid };
    })
```

**Comment by herudi** [comment]
related #49

**Comment by xyzshantaram** [comment]
It's definitely related, but the thing was that body was empty even before adding the `await request.json()` call, for no discernible reason. I'll try it with newRequest for the time being though, thank you!

**Comment by herudi** [comment]
hi @xyzshantaram, what the `content-type` your body?

**Comment by herudi** [comment]
Hi @xyzshantaram, 
i tested send json with size ~5mb working fine in `rev.body`. maybe your forgot set headers `content-type` to `application/json` in the client.
```ts
const res = await fetch(some_url, {
  method: "POST",
  body: JSON.stringify(myBigJson),
  // like ExpressJS, you must set content-type headers.
  headers: { "content-type": "application/json" }
});
```

ref => https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options

**Comment by xyzshantaram** [comment]
Alright, thank you! I will try that.
