### ISSUE TITLE
Please, provide an example of how to use nhttp react ssr with an ui component framework.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#76]
Please, provide an example of how to use or setup nhttp react ssr with an react ui component framework.

Here are some example of react UI component framework :

https://baseweb.design/getting-started/setup/

https://chakra-ui.com/

https://mui.com/

https://tw-elements.com/

https://ui.mantine.dev/

**Comment by herudi** [comment]
sorry I don't have time yet. but if ui-component is running with react 18+ and SSR, it should be possible. Just follow the instructions in the documentation for the UI-component.

**Comment by herudi** [comment]
i tested Chakra is working fine.
```tsx
// routes/chakra.tsx

import { Helmet } from "nhttp/jsx.ts";
import { type RequestEvent } from "nhttp";
import { Button, ChakraProvider } from "https://esm.sh/@chakra-ui/react@2.8.2";

export default function Chakra(rev: RequestEvent) {
  return (
    <ChakraProvider>
      <Helmet>
        <title>Wellcome Chakra UI</title>
      </Helmet>
      <Button colorScheme="red">Button From Chakra</Button>
    </ChakraProvider>
  );
}

```
