### ISSUE TITLE
'Could not resolve "/nhttp-node-react-ssr/components/counter.tsx"

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#78]
'Could not resolve "/nhttp-node-react-ssr/components/counter.tsx"

**Comment by herudi** [comment]
maybe you should run it in the `nhttp-node-react-ssr` dir. 
```bash
cd nhttp-node-react-ssr
npm run dev
```

**Comment by herudi** [comment]
Needs to be investigated. please provide information:
- create-nhttp version.
- Node version.
- OS name.

**Comment by herudi** [comment]
please, try starting a new project with the latest version of `create-nhttp`
```bash
npm create nhttp@latest
```

**Comment by herudi** [comment]
are you using the chakra UI style in the hydrate component like Counter.tsx ?

**Comment by herudi** [comment]
i tested on my linux it works fine.
please check inspect element.
