### ISSUE TITLE
rev.response.clearCookie('authToken') not clear the cookie

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#79]
when I used rev.response.clearCookie('authToken') to clear the cookie in the browser, it didn't work.

this is what worked for me :

    return rev.response
    .cookie("authToken", ``, {
            httpOnly: ['production', 'prod'].includes(process.env.NODE_ENV)
              ? true
              : false,
            maxAge: 0,
            encode: true,
            secure: ['production', 'prod'].includes(process.env.NODE_ENV)
              ? true
              : false,
          })
      .status(200)
      .send({
          message: 'Déconnecté avec succès.'
      });

**Comment by herudi** [comment]
hi @francelwebdev  you can check cookie via `rev.cookies` after clear. 
just clarify, `clear` is a not `delete`.

**Comment by herudi** [comment]
Just use clearCookie(name).
```ts
// before
Set-Cookie: token=my_token; HttpOnly; path=/

// after clear
Set-Cookie: token=; HttpOnly; path=/; max-age=0
```
This is example using cookie. 
```ts
import nhttp from "https://deno.land/x/nhttp@1.3.24/mod.ts";

const app = nhttp();

app.post("/sign", (rev) => {
  rev.response.cookie("session", { user: rev.body.username }, { encode: true });
  return rev.response.redirect("/admin")
})

app.get("/sign", (rev) => {
  rev.response.type("html");
  return `
    <form action="/sign" method="POST">
      <input name="username" required>
      <input name="password" required>
      <button type="submit">Sign</button>
    </form>
  `
})

app.get("/admin", (rev) => {
  if (!rev.cookies.session) {
    return rev.response.redirect("/sign")
  }
  rev.response.type("html");
  return `
    <h1>Hello ${rev.cookies.session.user}</h1>
    <a href="/logout">Logout</a>
  `
});

app.get("/logout", ({ response }) => {
  response.type("html");
  response.clearCookie("session");
  response.status(401);
  return `<h1>Logout Success...</h1>
    <br/>
    <a href="/sign">Goto Sign</a>
  `;
});

app.listen(8000)
```

hope this help.

**Comment by herudi** [comment]
in middleware, check using this :
```ts
if (!rev.cookies.session) {
    return rev.response.redirect("/sign")
 }
```
