### ISSUE TITLE
CORS errors after a long inactivity on the nhttp api server using nhttp + nodejs.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#84]
CORS errors after a long inactivity on the nhttp api server using nhttp + nodejs.

Access to fetch at 'https://api.ciexchange.francel.xyz/api/users/login/passwordless' from origin 'https://ciexchange.francel.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by herudi** [comment]
Make sure you have used cors libs.

**Comment by herudi** [comment]
weird... please screenshot the response header. maybe set maxAge.

**Comment by herudi** [comment]
do you use helmet?

try set crossOriginResourcePolicy to false.

**Comment by herudi** [comment]
check your origin config. maybe not detected from your server.

**Comment by herudi** [comment]
origin `boolean` or `string`
```ts
origin: (rev: RequestEvent) => {
    const origin = rev.request.headers.get('Origin');
    return allowedOrigins.includes(origin) ? origin : false
},
})
```

**Comment by herudi** [comment]
you can check origin. maybe is `null`
```ts
origin: (rev: RequestEvent) => {
    const origin = rev.request.headers.get('Origin');

    console.log(origin);

    return allowedOrigins.includes(origin) ? origin : false
}
```

**Comment by herudi** [comment]
what do you get from the log `console.log(origin)` ?

**Comment by herudi** [comment]
fetch configuration that you use on the frontend? I tried it with a case like yours. it works fine.

**Comment by herudi** [comment]
there is no 'Access-Control-Allow-Origin' headers. check your response.

**Comment by herudi** [comment]
test using `rev.response.setHeader("Access-Control-Allow-Origin", "*");`

**Comment by herudi** [comment]
your error message `No 'Access-Control-Allow-Origin' header is present on the requested resource`. This means you don't set allow origin from your server. please check again `allowedOrigins.includes(origin)`.
