### ISSUE TITLE
How to redirect to another page after sending form request to api route when using nhttp + react ssr ?

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#87]
Hi @herudi ,

How to redirect to another page after I submit a form in a component via a http client to api route when using nhttp + react ssr ?

**Comment by herudi** [comment]
just redirect via client like `window.location.href`.

**Comment by herudi** [comment]
Basically, this uses partial hydration, not SPA. so you can pass data via session or local storage.
