### ISSUE TITLE
Cannot set multiple cookies at once.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#88]
Hi @herudi 

I'm trying nHttp + react ssr and currently I cannot set multiple cookies at once.

import { Helmet } from "nhttp-land/jsx";
import { type RequestEvent } from "nhttp-land";
import Layout from "components/layout.tsx";
import axios from 'axios';
import { parse } from '@lukeed/ms';

export default function validateAccountConfirmationToken(rev: RequestEvent) {
    const protocol = ['production', 'prod'].includes(process.env.NODE_ENV)
        ? 'https'
        : 'http'

    const validateAccountConfirmationToken = async () => {
        try {
            const response = await fetch(`${protocol}://${rev.request.headers.get('host')}/api/auth/validate-account-confirmation-token`, {
                method: "POST",
                body: JSON.stringify({
                    token: rev.query.token
                })
            })

            const responseData = await response.json()

            rev.response
                .cookie("flashNotification", { type: "SUCCESS", message: "Compte confirmé avec succès." }, {
                    // httpOnly: ['production', 'prod'].includes(process.env.NODE_ENV)
                    //   ? true
                    //   : false,
                    httpOnly: false,
                    maxAge: parse('5s'),
                    encode: true,
                    domain: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? 'cicagnotte.francel.xyz'
                        : 'localhost',
                    secure: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? true
                        : false,
                    sameSite: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? "None"
                        : "Lax",
                })
                .cookie("session", { userId: responseData.data.id }, {
                    // httpOnly: ['production', 'prod'].includes(process.env.NODE_ENV)
                    //   ? true
                    //   : false,
                    httpOnly: false,
                    maxAge: parse('1d'),
                    encode: true,
                    domain: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? 'cicagnotte.francel.xyz'
                        : 'localhost',
                    secure: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? true
                        : false,
                    sameSite: ['production', 'prod'].includes(process.env.NODE_ENV)
                        ? "None"
                        : "Lax",
                });

            return rev.response.redirect("/transactions")
        } catch (error) {
            console.log("error", error)

            return rev.response.redirect("/auth/login")
        }
    }

    (async () => {
        await validateAccountConfirmationToken()
    })()

    // return (
    //     <>
    //         <Layout>
    //             <Helmet>
    //                 <title>Login</title>
    //             </Helmet>

    //             <div className="container mx-auto p-8 h-full">
    //                 <div className="columns-1">

    //                     <button className="btn btn-square">
    //                         <span className="loading loading-spinner"></span>
    //                     </button>

    //                 </div>
    //             </div>

    //         </Layout>
    //     </>
    // )
}

**Comment by herudi** [comment]
what runtime are you using?

**Comment by herudi** [comment]
fix #89 . update nhttp to `1.3.26`. if you found issue, please re-open.

**Comment by herudi** [comment]
yes.
