### ISSUE TITLE
A bug with nhttp + react ssr with nodejs.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#90]
Hello @herudi 

I have a bug with nhttp + react ssr with nodejs.

I have a Navbar component in the components folder that I imported into the Layout component which is also in the components folder.

In the Navbar component, I have a button, when I click on the button it doesn't work.

Below is the button code

`<button className="btn btn-error" onClick={() => alert("hello")}>Se déconnecter</button>`

The alert() not showing.

**Comment by herudi** [comment]
maybe forgot re-hydration components. 
`export default withHydrate(MyComponent, import.meta.url);`

**Comment by herudi** [comment]
try to import Navbar in the routes.
