### ISSUE TITLE
JSR

### ISSUE THREAD

**Issue by shevernitskiy** [nhttp/nhttp#91]
I've noticed empty package on JSR. Is there any obstacles to upload it? Also i've noticed, that there is no release ci, maybe it is a good reason to make it:)

**Comment by herudi** [comment]
Last month, I published to JSR but it didn't work. Maybe at that time JSR was in the development stage. but I'll try again later.

of course, but for now I'm trying to release it locally.

Thanks for the advice.

**Comment by herudi** [comment]
hi @shevernitskiy, i published nhttp to jsr => https://jsr.io/@nhttp/nhttp. but in alpha stage v0.0.1.
facts about [jsr](https://jsr.io) for now :
- `slow types` ts restriction.
- Module augmentation and global augmentation not work. e.g `declare global` or `module`.

**Comment by shevernitskiy** [comment]
Nice, thanks! Will use it:)

**Comment by herudi** [comment]
please create a new issue if you find any bugs from `jsr:@nhttp/nhttp`.

**Comment by shevernitskiy** [comment]
Oh, it's so nice that i can jump to actual ts source code but not the compiled types and generated unreadable js:)
