### ISSUE TITLE
deno.json with JSR

### ISSUE THREAD

**Issue by shevernitskiy** [nhttp/nhttp#92]
Current docs a bit irrelevant with JSR now.

Now you need to import just `@nhttp/nhttp`.  At the first attempt i got an issue with `nhttp-jsx/jsx-runtime`.
But we need just define libs in compilerOpions and don't need any additional imports to deal with it.
```json
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "@nhttp/nhttp/jsx",
    "lib": ["dom", "dom.iterable", "deno.ns"]
  },
```

**Comment by herudi** [comment]
nice info. 
in v2, I plan to focus on jsr. I'm sure, slowly but surely, `deno.land/x` will be replaced by `jsr.io`.

for now, `deno.land/std` available in `jsr.io/@std`.

**Comment by herudi** [comment]
now, available in https://jsr.io/@nhttp/nhttp
