### ISSUE TITLE
error in nhttp api only poject in a route handler

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#93]
Hello @herudi , hope you fine.

I'm currently facing an error in nhttp api only poject in a route handler where i use https://arctic.js.org/providers/google for user auth.

I get the error below when I'm using arcticGoogle.validateAuthorizationCode()

![Screenshot_from_2024-05-28_12-33-41](https://github.com/nhttp/nhttp/assets/18377068/e2ce6612-4a36-4a68-b7a0-a01d5164b0ee)

![Screenshot_from_2024-05-27_21-57-57](https://github.com/nhttp/nhttp/assets/18377068/50180f3f-6ac8-4580-ba70-7c0a3d362b31)

**Comment by herudi** [comment]
yeah.
