### ISSUE TITLE
Can not install nhttp after migrate to new version

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#97]
![Screenshot from 2024-06-13 14-41-39](https://github.com/nhttp/nhttp/assets/18377068/d6b4e6ef-a31c-4641-bd94-dd50567d76af)

**Comment by herudi** [comment]
please try again with `npm create nhttp@latest`. 

ref => https://github.com/nhttp/create-nhttp/releases/tag/0.1.1
