### ISSUE TITLE
The Request.method getter can only be used on instances of Request

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#98]
I'm currently having this error when my nhttp bun receive an request from the vue frontend. Evryting working well ealier.

![Screenshot from 2024-06-14 15-02-33](https://github.com/nhttp/nhttp/assets/18377068/0953808f-b4e9-4df8-b97e-7a5ad5c13264)

**Comment by herudi** [comment]
hi @francelwebdev , This error not related to NHttp. i try using `console.log(rev);` its works fine.
