### ISSUE TITLE
I can't add or update any npm package when use the new nhttp version that use jsr.

### ISSUE THREAD

**Issue by francelwebdev** [nhttp/nhttp#99]
Hi @herudi ,
I can't add or update any npm package when use the new nhttp version that use jsr.

**Comment by herudi** [comment]
Hi @francelwebdev , sorry about that. i fix again in  [0.1.2](https://github.com/nhttp/create-nhttp/releases/tag/0.1.2). so, you can try with `npm create nhttp@latest`. thanks.
